# Generated by Django 2.1.7 on 2019-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgnisation_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('org_domain', models.CharField(max_length=150)),
            ],
        ),
    ]
