# Generated by Django 2.1.7 on 2019-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_capitalistinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalistinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisationinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
